// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXT4BsxF5YCk27Dpmy2mvKQ88HHmSFTEI',
    appId: '1:772163012624:web:8b09a175cf2927d7342295',
    messagingSenderId: '772163012624',
    projectId: 'streaming-1d47e',
    authDomain: 'streaming-1d47e.firebaseapp.com',
    storageBucket: 'streaming-1d47e.appspot.com',
    measurementId: 'G-75TQ5M08GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0KtdVnDk6fs-XipmjXIumx7fPdzjT9M',
    appId: '1:772163012624:android:f8392cd1be3a9564342295',
    messagingSenderId: '772163012624',
    projectId: 'streaming-1d47e',
    storageBucket: 'streaming-1d47e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_5eJ1NFS6tieSX7wyjR8dh-LSuVFJu-c',
    appId: '1:772163012624:ios:b0a375fdd766d3f5342295',
    messagingSenderId: '772163012624',
    projectId: 'streaming-1d47e',
    storageBucket: 'streaming-1d47e.appspot.com',
    iosBundleId: 'com.example.movieStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_5eJ1NFS6tieSX7wyjR8dh-LSuVFJu-c',
    appId: '1:772163012624:ios:b0a375fdd766d3f5342295',
    messagingSenderId: '772163012624',
    projectId: 'streaming-1d47e',
    storageBucket: 'streaming-1d47e.appspot.com',
    iosBundleId: 'com.example.movieStreaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXT4BsxF5YCk27Dpmy2mvKQ88HHmSFTEI',
    appId: '1:772163012624:web:4752e22543213dbe342295',
    messagingSenderId: '772163012624',
    projectId: 'streaming-1d47e',
    authDomain: 'streaming-1d47e.firebaseapp.com',
    storageBucket: 'streaming-1d47e.appspot.com',
    measurementId: 'G-T1S17ZXQP5',
  );
}
